version: "3.8"

services:
  web:
    container_name: zock-studio
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3000

    networks:
      - webnet
    environment:
      NODE_ENV: production
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
